### ISSUE TITLE
🐛 Fix "Update Google Sheet + Database with SEC Data" Workflow 

### ISSUE THREAD

**Issue by JamesAlfonse** [WhyDRS/Database#24]
About a week about this error started popping up when fetching SEC data. Not sure why it's happening now. Could it be that there's two entries with the same CIK and ticker? Should there be a third key established for issuer name to resolve this issue?

![Screenshot 2024-10-25 at 12 38 21 AM](https://github.com/user-attachments/assets/d19f74de-45bc-4e7b-9cfe-00239ea2141c)

**Comment by JamesAlfonse** [comment]
Seems to have been caused by a duplicate entry. I deleted the duplicate entry from the Google sheet, but the .db file still has the two entries. MGR was listed twice, unsure why/how that happened now. Last time this happened I had to download the file and manually delete the rows, then reupload the file. Would love to figure out a better way to resolve this in the future (maybe using bigquery solves this?).

**Comment by JFWooten4** [comment]
Ah, yes, I see how this implicates the entire query design system. Thanks for digging in deep to the logging errors here! It sounds like you've gone through the ringer on ensuring data accuracy. 🕵️

**Comment by JamesAlfonse** [comment]
It works again. The database now has three primary keys, the CIK, the Ticker, and the Company Name. I split these files into two different workflows, one that syncs the database with the Google sheet, and one that updates the database with the SEC data. The first one happens at 23:30 and the second one at 0:00 UTC. The sync has a section for Source of Truth columns that take precedence and update the Sheet with this data (case-insensitive, with the database case type taking priority). The SEC data updates are case-insensitive, with the SEC case type taking priority and the data from the SEC taking priority. Merge conflicts after that are handled by adding a new row.
