### ISSUE TITLE
minor display issue

### ISSUE THREAD

**Issue by bobmahalo** [WhyDRS/Database#26]
https://github.com/user-attachments/assets/4f65da4b-e158-4d7e-b12a-6e4dc9538870

aloha, just perusing the website, and this is definitely low priority. but wanted to bring it up, as a blemish in the paint job.... the top heading is hidden. I tried other pages, and it is not hidden?

**Comment by JFWooten4** [comment]
Love the vid @bobmahalo!! 🎥
cc: wix config @tehchives 🖥️

**Comment by tehchives** [comment]
Thanks for sharing this Bob! The video really helps to immediately illustrate the issue. 

I am checking into it now.

**Comment by tehchives** [comment]
Okay, that was a quick fix! Should be better now. Thank you again Bob for bringing this up!

Page in question: https://www.whydrs.org/what-is-drs

**Comment by tehchives** [comment]
Resolved
