### ISSUE TITLE
✏️ Preference for documentation coding language : Javascript v Typescript

### ISSUE THREAD

**Issue by JFWooten4** [WhyDRS/Database#28]
Also I raised the point on using JS or TS,[^lang] which should probably be put to a vote imo with implications if:

- (i) They need to be the same between all folders in the monorepo and
- (ii) It's matrailly-difficult ot change between one option andf anther
- (iii) Other implications you can think of? 💭

[^lang]: AFAIK our repos and imports chiefly use JS. _See_ [docs](https://github.com/WhyDRS/DAO-docs/commit/31122d38fd2c61ca71fbfd3d12c598c64ce3d82f), [data(_?_)](https://github.com/WhyDRS/drs-data/blob/main/docs/index-fcca9ef4.js) @apes-on-parade, and [minor discussion](https://discordapp.com/channels/1102309240145707049/1262090921688961034/1283945073092071445).

Not the largest frontend guy, so I'll certainly defer to those like Throw[^n] if this matters much now.

[^n]: My bad on the random ping initially, and hope you have a stellar weekend out and about!

**Comment by JFWooten4** [comment]
this seems irrelevant to the DB and most certainly not a choice that should be made in a centralized manner like this, given/assuming/if nobody cares enough to comment at this point

considering closing it & can always reference later if pops up

**Comment by JamesAlfonse** [comment]
@JFWooten4 Thinking this should be closed for now and reopened later if needed. Or moved to the Ideas To Explore column.

**Comment by JFWooten4** [comment]
Inspired by DUNA site config at https://github.com/WhyDRS/DAO-docs/commit/31122d38fd2c61ca71fbfd3d12c598c64ce3d82f, now outdated.
