### ISSUE TITLE
Explanation for blank spaces in database (e.g. no transfer agent or info not available?) and then link Contribution Form from WhyDRS.org/database

### ISSUE THREAD

**Issue by greengiantyo** [WhyDRS/Database#30]
Chives was giving me a tutorial on how to use GitHub and this is something that popped out to me while browsing database.WhyDRS.org. 

I think users may have questions on why there are blank spaces. Maybe a placeholder something to the effect of [unknown] or [info unavailable] or [need volunteer to find]. 

Also, maybe we can add a direct link to the "old" Contribution Form through google docs.

**Comment by tehchives** [comment]
Love this idea! If filling the blanks in makes it look too busy, maybe we can add some text explaining that the blanks mean that we still need that data to be added or contributed, and then make sure to link out to the form pages to submit data.

**Comment by greengiantyo** [comment]
Yes, could be too busy maybe. If it's small enough (small .jpg possibly?) or maybe have a legend somewhere with just small symbols e.g. *, #, etc... as representative.

**Comment by JamesAlfonse** [comment]
Great ideas @greengiantyo ! I agree, there should be a link to the contribution form within the database page. I can also add an asterisk on the page to point out that blank spots still need to be filled out.

**Comment by greengiantyo** [comment]
Sounds good. Yes, I think if/when others see that the "blank spots" aren't filled out but CAN BE by .... themselves ... it could be a cool catalyst. Maybe there's something we can do along those lines further - or maybe something more ~explicit like having on every other page at the bottom a memo **_"WhyDRS is 100% volunteer run. We need your help. Click here to learn more."_**

**Comment by tehchives** [comment]
> Sounds good. Yes, I think if/when others see that the "blank spots" aren't filled out but CAN BE by .... themselves ... it could be a cool catalyst. Maybe there's something we can do along those lines further - or maybe something more ~explicit like having on every other page at the bottom a memo **_"WhyDRS is 100% volunteer run. We need your help. Click here to learn more."_**

I love this! Maybe we could tie in a link out to the DUNA and GitHub, and help grow more interest in those spaces as well. The Database is like a 'killer app' so angling for a positive feedback loop would be really helpful.

**Comment by JamesAlfonse** [comment]
I made a branch and deployed it to fleek, looking for some feedback on this before merging to main. I added links to the google form for contributions, the whydrs email address, and a link to the github on the bottom. What are your thoughts? @greengiantyo @tehchives @JFWooten4 

https://numerous-zoo-large.on-fleek.app/

![Screenshot 2024-11-24 at 3 47 23 PM](https://github.com/user-attachments/assets/f25e1682-98e9-4828-8f19-f130d84a3b64)

![Screenshot 2024-11-24 at 3 47 34 PM](https://github.com/user-attachments/assets/b6a868e1-7cf6-4ca7-b4ce-2b7776330cf5)

**Comment by tehchives** [comment]
This looks fantastic!! Front, top and center exactly where I think we would want it to be. Great work!

Maybe mention in the footer more specifically that all code can be reviewed / suggestions can be made on the GitHub? That might get more clicks than the 'learn more'. Not sure though. Hard to say what would incite more clicks!

**Comment by JamesAlfonse** [comment]
Agreed, it might be good to workshop the footer text. How about something like:

"WhyDRS is 100% volunteer-driven. Help us improve by contributing or providing feedback [on GitHub](https://github.com/WhyDRS/Database/tree/main). Join us today!"

Alternatively, "on Github" can be changed to "here" so that the word "Github" is avoided as an initial barrier to entry

**Comment by tehchives** [comment]
> Alternatively, "on Github" can be changed to "here" so that the word "Github" is avoided as an initial barrier to entry

I think that's perfect. GitHub itself being the barrier was exactly what I was concerned about, but couldn't put words to!

**Comment by JamesAlfonse** [comment]
Here's a visual with the update

![Screenshot 2024-11-24 at 4 08 03 PM](https://github.com/user-attachments/assets/e283c7c4-121f-402f-9210-fcaea1fd1261)

https://numerous-zoo-large.on-fleek.app/
