### ISSUE TITLE
🎨 Enhance Table Design to Reflect WhyDRS Brand Colors and Modern Aesthetics

### ISSUE THREAD

**Issue by JamesAlfonse** [WhyDRS/Database#7]
The current table design in our application lacks visual cohesion with the WhyDRS brand and modern UI trends. This issue aims to update the table's appearance to improve user engagement and brand consistency.

**Tasks:**

- **Color Scheme:** Change the header row background to our branded blue color with white text for better visibility and brand alignment.
- **Rounded Corners:** Apply rounded corners to the table to give it a more contemporary look.
- **Visual Enhancements:** Introduce a color gradient or a subtle "bubble" effect in the header row to make the UI more appealing and dynamic.

**Expected Outcome:** A visually appealing table that aligns with the WhyDRS brand colors, enhancing the overall user experience and maintaining consistency across our digital platforms.

**Comment by JFWooten4** [comment]
Here are the colors by my understanding:
- 🔵 Blue: #134F9B
- ⚫ Black: #2B2B2B
- There [might be](https://github.com/WhyDRS/DAO-docs/issues/4) other established colors from, e.g., the present [explainer](https://youtu.be/c6-jRueHIUI)?

If this is correct @tehchives, then we can incorporate into the [docs](https://github.com/WhyDRS/DAO-docs), too.

**Comment by tehchives** [comment]
144f9b is the blue in the main logo, and 2b2b2b is the black in the main logo. 

I took a look at the website and in the body of articles, we use a different blue and a different black for headings and text. In those cases, the heading is a blue with hex of 005BA9 and the text is a black with hex of 3E3E3E

In the explainer video we have on the homepage, a different blue with a hex of 104C85 was used for the Transfer Agent box and some other graphics. The logo at the end of the video uses the 144f9d and the 2b2b2b that you identified.

**Comment by JFWooten4** [comment]
@tehchives So `005BA9` is something we want to keep using? Feel free to edit directly in formalization at https://github.com/WhyDRS/DAO-docs/blob/main/imgs/brand/colors.md

Thank you and @BibicJr for the quick info! 🤝

**Comment by JamesAlfonse** [comment]
Closing issue and continuing improvements in issue #17
